name = "instatomdnotes-worker"
main = "index.js"
compatibility_date = "2024-01-01"

account_id = "a0d2686f0804c32456ef0f58975e9853"

[[kv_namespaces]]
binding = "QUEUE"
id = "897dcd24fa784dbc90f32d4d6cb0db21"
